# Generated by Django 5.1.4 on 2024-12-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('I', 'Class I'), ('II', 'Class II'), ('III', 'Class III'), ('IV', 'Class IV'), ('V', 'Class V'), ('VI', 'Class VI'), ('VII', 'Class VII'), ('VIII', 'Class VIII'), ('IX', 'Class IX'), ('X', 'Class X')], max_length=5),
        ),
    ]
