# Generated by Django 5.1.4 on 2024-12-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_staff_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('LP', 'Lower Primary'), ('UP', 'Upper Primary'), ('HS', 'High School')], max_length=100),
        ),
    ]
