# Generated by Django 5.1.4 on 2024-12-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_librarian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='salary',
        ),
    ]
